Suggesting an error message solution
adafruit/Adafruit_CircuitPython_PCA9685 pull request #47
Opened 2022-12-13 17:56 UTC by tcfranks

resolves #29 
submitted for review / comment.

My 2 cents.  it appears the only way the prescale_reg value can go south (it's read when invoked, I think) would be for I2C to fail.  According the the specsheet for PCA9685 chip, the register should be in the range of  0x03 <= value <= 0xFF.  I've only suggested for the low end, but to be airtight do we want to go the full way?   (spec sheet p 25 of 52)

2022-12-13 17:58 UTC, tcfranks commented
also, the frequency setter already checks against trying to prescale a value < 3, but does not check the prescale result of > 255.

2023-01-06 17:40 UTC, tekktrik requested changes
One minor change, but looks good!

2023-01-06 17:40 UTC, tekktrik commented on adafruit_pca9685.py
> +            raise ValueError(f"Out of range: value {value} not 0 <= value <= 0xFFFF")
I like the change, but let's use decimal instead of hex since that's more beginner friendly.

2023-01-06 18:00 UTC, tcfranks commented
@tekktrik in florida for 10 days with only a phone. Will tend to this when I get home!

2023-01-15 14:49 UTC, tcfranks commented
submitted for review of suggested mod

2023-01-15 21:30 UTC, tekktrik approved these changes
Thanks for the helpful update!

2023-01-15 21:30 UTC, merged